# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 07:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254)),
                ('joining_date', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('birthdate', models.DateField()),
                ('Address', models.TextField()),
                ('designation', models.CharField(max_length=254)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='company.Employee')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterUniqueTogether(
            name='employee',
            unique_together=set([('id', 'parent')]),
        ),
    ]
