# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-18 07:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='Address',
            new_name='address',
        ),
    ]
